Update to package json to pin eventemitte3
Loading "connect_proxy.js" tasks...ERROR
>> TypeError: The super constructor to `inherits` must not be null or undefined.
>>     at Object.exports.inherits (util.js:752:11)
>>     at Object.<anonymous> (/Users/sonnyfraikue/Documents/projects/generatorangularphp/node_modules/http-proxy/lib/http-proxy/index.js:106:17)
>>     at Module._compile (module.js:413:34)
>>     at Object.Module._extensions..js (module.js:422:10)
>>     at Module.load (module.js:357:32)
>>     at Function.Module._load (module.js:314:12)
>>     at Module.require (module.js:367:17)
>>     at require (internal/module.js:16:19)
>>     at Object.<anonymous> (/Users/sonnyfraikue/Documents/projects/generatorangularphp/node_modules/http-proxy/lib/http-proxy.js:4:17)
>>     at Module._compile (module.js:413:34)